spring:
  application:
    name: "notification"
  mail:
    host: smtp.gmail.com
    port: 587
    username: your-email@gmail.com
    password: your-email-password
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    url: jdbc:postgresql://localhost:5435/notification-db
    username: postgres
    password: password
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
