server:
  port: 9020

spring:
  application:
    name: "report-service"
  datasource:
    url: jdbc:postgresql://localhost:5434/report-db
    username: postgres
    password: password
  jpa:
    show-sql: true
  sql:
    init:
      mode: always


feign:
  client:
    config:
      tasks:
        connect-timeout: 3000
        read-timeout: 3000
        logger-level: DEBUG
