server:
  port: 9020

spring:
  application:
    name: "user-service"
  datasource:
    url: jdbc:postgresql://localhost:5433/user-db
    username: postgres
    password: password
  jpa:
    show-sql: true
  sql:
    init:
      mode: always



















