server:
  port: 8080

spring:
  application:
    name: "task-service"
  datasource:
    url: jdbc:postgresql://localhost:5432/task-db
    username: postgres
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud:
    stream:
      bindings:
        taskSendNotification-out-0:
          destination: task-notification-topic
        taskCreateReport-out-0:
          destination: task-report-topic
      kafka:
        binder:
          brokers:
            - localhost:9092
  kafka:
    bootstrap-servers: localhost:9092
